server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:1521/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
    
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 776826857924-lueh0unv4curaom2lr8bqdjuobseu6ng.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          
    
